#!/usr/bin/env bash
# =============================================================================
# scripts/post-apply.sh — capture terraform outputs → infra-live-outputs.txt
#
# Run after every terraform apply:
#   bash scripts/post-apply.sh
#
# Output file: infra-live-outputs.txt (repo root)
# Format: KEY=value — grep the key you need:
#   grep "^IAM_GITHUB_ACTIONS_ROLE_ARN=" infra-live-outputs.txt | cut -d= -f2
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="${REPO_ROOT}/terraform/environments/dev"
OUT_FILE="${REPO_ROOT}/infra-live-outputs.txt"

echo "Running terraform output..."
cd "${TF_DIR}"

# Helper — plain output
tf() { terraform output -raw "$1" 2>/dev/null || terraform output -json "$1" 2>/dev/null | tr -d '"[]' | tr ',' '\n' | xargs; }

cat > "${OUT_FILE}" << EOF
# =============================================================================
# infra-live-outputs.txt — generated by scripts/post-apply.sh
# Generated : $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# Environment: dev
# DO NOT EDIT MANUALLY — re-run scripts/post-apply.sh after terraform apply
# =============================================================================

# ── AWS Account ───────────────────────────────────────────────────────────────
AWS_ACCOUNT_ID=$(terraform output -raw aws_account_id)
AWS_REGION=$(terraform output -raw aws_region)

# ── VPC / Networking ──────────────────────────────────────────────────────────
VPC_ID=$(terraform output -raw vpc_id)
VPC_CIDR=$(terraform output -raw vpc_cidr)
PUBLIC_SUBNET_IDS=$(terraform output -json public_subnet_ids | jq -r 'join(",")')
ALB_SECURITY_GROUP_ID=$(terraform output -raw alb_security_group_id)
INTERNET_GATEWAY_ID=$(terraform output -raw internet_gateway_id)
PUBLIC_ROUTE_TABLE_ID=$(terraform output -raw public_route_table_id)

# ── EKS ───────────────────────────────────────────────────────────────────────
EKS_CLUSTER_NAME=$(terraform output -raw eks_cluster_name)
EKS_CLUSTER_ENDPOINT=$(terraform output -raw eks_cluster_endpoint)
EKS_CLUSTER_ROLE_ARN=$(terraform output -raw eks_cluster_role_arn)
EKS_NODE_GROUP_NAME=$(terraform output -raw eks_node_group_name)
EKS_NODE_ROLE_ARN=$(terraform output -raw eks_node_role_arn)
EKS_CLUSTER_SECURITY_GROUP_ID=$(terraform output -raw eks_cluster_security_group_id)
EKS_NODE_SECURITY_GROUP_ID=$(terraform output -raw eks_node_security_group_id)
EKS_OIDC_PROVIDER_ARN=$(terraform output -raw eks_oidc_provider_arn)
EKS_OIDC_PROVIDER_URL=$(terraform output -raw eks_oidc_provider_url)
EKS_CLUSTER_CA_DATA=$(terraform output -raw eks_cluster_certificate_authority_data)

# ── ECR ───────────────────────────────────────────────────────────────────────
ECR_ENVIRONMENT_PREFIX=$(terraform output -raw ecr_environment_prefix)
ECR_REPOSITORY_URLS=$(terraform output -json ecr_repository_urls | jq -r 'to_entries[] | "\(.key)=\(.value)"' | tr '\n' ' ')

# ── RDS ───────────────────────────────────────────────────────────────────────
RDS_ENDPOINT=$(terraform output -raw rds_endpoint)
RDS_PORT=$(terraform output -raw rds_port)
RDS_DATABASE_NAME=$(terraform output -raw rds_database_name)
RDS_MASTER_USERNAME=$(terraform output -raw rds_master_username)
RDS_SECRET_ARN=$(terraform output -raw rds_secret_arn)
RDS_SECURITY_GROUP_ID=$(terraform output -raw rds_security_group_id)

# ── IAM Roles ─────────────────────────────────────────────────────────────────
IAM_GITHUB_ACTIONS_ROLE_ARN=$(terraform output -raw iam_github_actions_role_arn)
IAM_GITHUB_ACTIONS_TF_ROLE_ARN=$(terraform output -raw iam_github_actions_tf_role_arn)
IAM_ESO_ROLE_ARN=$(terraform output -raw iam_eso_role_arn)
IAM_LB_CONTROLLER_ROLE_ARN=$(terraform output -raw iam_lb_controller_role_arn)
IAM_EBS_CSI_ROLE_ARN=$(terraform output -raw iam_ebs_csi_role_arn)

# ── Karpenter ─────────────────────────────────────────────────────────────────
KARPENTER_CONTROLLER_ROLE_ARN=$(terraform output -raw karpenter_controller_role_arn)
KARPENTER_NODE_ROLE_ARN=$(terraform output -raw karpenter_node_role_arn)
KARPENTER_NODE_INSTANCE_PROFILE_ARN=$(terraform output -raw karpenter_node_instance_profile_arn)
EOF

echo ""
echo "✓ Written to: ${OUT_FILE}"
echo ""
echo "Key values:"
grep -E "^(IAM_GITHUB_ACTIONS_ROLE_ARN|IAM_GITHUB_ACTIONS_TF_ROLE_ARN|RDS_SECRET_ARN|RDS_ENDPOINT|EKS_CLUSTER_NAME|ECR_ENVIRONMENT_PREFIX)=" "${OUT_FILE}"
